version: '3'

services:
  django:
    container_name: django_mongoengine_filter_django
    image: django_elasticsearch_dsl_drf_backend:latest
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/backend
      - ./docker/django:/docker/django
    ports:
      - "8000:8000"
    depends_on:
    - mongo
    links:
      - mongo:mongo
    entrypoint:
      - /backend/docker/django/entrypoint.sh
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker

  mongo:
    container_name: django_mongoengine_filter_mongodb
    image: mongo
    restart: always
    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_DATA_DIR=/var/db
      - MONGO_LOG_DIR=/var/logs
    volumes:
      - ./var/db:/var/db
      - ./var/logs:/var/logs
    ports:
      - 27017:27017
