version: '3'

services:

  mongo:
    image: mongo:5
    restart: always
    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_DATA_DIR=/var/db
      - MONGO_LOG_DIR=/var/logs
    volumes:
      - ./var/db:/var/db
      - ./var/logs:/var/logs
    ports:
      - 27017:27017
